### ISSUE TITLE
Subscription Module : New Reports needed

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#1019]
similar to existing report but for specific filters
- Active Subscriptions as per 'DeliveryBy' ie from the autocomplete drop down the deliveryBy would be chosen
- All Subscriptions as per 'EnrolledBy' ie from the autocomplete drop down the enrolledBywould be chosen, also show enrollmentDate
- Subscriptions expiring <= 2months (or 1 month) as per user choice; here show both delivery by and enrolledby+date in the report
- expired subscriptions (those whose till date is over and the subscriber has no other active (on the basis of dates) subscription for the same periodical) sample query:
select se.* from subscription se where se.till<='2020-12-31 23:59:59' and not exists (select 1 from subscription sc where sc.since>='2019-12-18 00:00:00' and sc.subscriber_id=se.subscriber_id)

replace the date by current date

**Comment by susanta4** [comment]
4 option needs to be checked
