### ISSUE TITLE
Event Module : Config data

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#1031]
Have a page (link on event/show page) to capture the config data for the event in AV as per the following list:

existing attributes
--------------------
numDays=4
prasadCostPerDay=325
travelCostPerDay=425
venueCostPerDay=325
numPlaces=2
place1=Dwarka
place1_numDays=2
place1_nonacRoomRentPerDay=500
place1_acRoomRentPerDay=1000
place1_nonacRoomNumBeds=2
place1_nonacRoomNumExtraBeds=1
place1_nonacRoomExtraBedRentPerDay=50
place1_acRoomNumBeds=2
place1_acRoomNumExtraBeds=1
place1_acRoomExtraBedRentPerDay=100
place1_numNonACRooms=100
place1_numACRooms=100
place2=Somnath
place2_numDays=1
place2_nonacRoomRentPerDay=700
place2_acRoomRentPerDay=1000
place2_nonacRoomNumBeds=2
place2_nonacRoomNumExtraBeds=1
place2_nonacRoomExtraBedRentPerDay=50
place2_acRoomNumBeds=2
place2_acRoomNumExtraBeds=1
place2_acRoomExtraBedRentPerDay=100
place2_numNonACRooms=100
place2_numACRooms=100

Also, following new attributes to be created (these if 'yes' means that the participant has to exercise the choice, else if 'no' means that participants have no or limited choices...will explain logic in detail later on
-----------------------------------------------
accommodationOptional = yes or no
prasadamOptional = yes or no
travelOptional = yes or no

**Comment by susanta4** [comment]
2 nd option not done
