### ISSUE TITLE
EMS Module -EAR creation.. Submit button remains disabled in case of a validation error

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#121]

**Comment by pkaushal** [comment]
The code change done 'enables' it for all scenario...
The correct behaviour is that the button is enabled only if there are validation errors...else in 'all ok' scenario the submit button should get disabled after it has been clicked once..

**Comment by susanta4** [comment]
done!

**Comment by pkaushal** [comment]
It is not showing the alerts..i think the logically what you did is correct but maybe it should be in the create.gsp rather than _addproject.gsp...
also pls test thoroughly (i.e. end to end flow)  before sending else I end up doing  debugging...
