### ISSUE TITLE
DonationModule: SM sub-module related enhancements..

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#1234]
- Bulk upload in the enrollment page on server should be verified to be consistent with the fields on the form
- On the app, verify 'CreateDonation' (ie collection of donation from a donor by a collector) is working or not. Also, add support for paymentComments (a_<counsumerNumber>=<amt>##...)
- On app, equivalent of the enrollment page for SchemeMembership creation ( i guess some page was there, we need to use the same page for self enrollment or enrolling someone else)

PS:
pls dont commit the changes on app unless we have reviewed/demo

**Comment by susanta4** [comment]
paymentComments field is added and manual input (a_=##...) is required to support multiple scheme
