### ISSUE TITLE
EMS Module: Pull IDT config

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#1366]
login as hod, then from the EMS dashboard, navigate to PullIDT (/invoice/departmentalDirectIDTList)...
the list of 'From cost centers' should be shown as per config ...but its showing all deps as of now..this has to be fixed..

finhead can do the config from, emsdashboad/directidt/configue -> project/configDirectIDTCostCenters

**Comment by susanta4** [comment]
First need to be configured using http://localhost:8080/ics/project/configDirectIDTCostCenters , if not configured, will take all cc pls see invociecontroller line no 2299 onwards.
