### ISSUE TITLE
KMS Module: Multiple issues..

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#1409]
pls fix as many as possible from the attached list..pls look at all issues (Across multiple files / sheets) and then work on simple ones first

[ICS.pdf](https://github.com/kstsvcs/ics/files/6652558/ICS.pdf)
[kms errors.xlsx](https://github.com/kstsvcs/ics/files/6652560/kms.errors.xlsx)
[Error's in ICS Software.xlsx](https://github.com/kstsvcs/ics/files/6652576/Error.s.in.ICS.Software.xlsx)

**Comment by susanta4** [comment]
Excel cooking sheet alignment others are fixed..
