### ISSUE TITLE
Jivadaya Module - Autofollowup 

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#191]
similar to MB/job

distributor should get comms 10 days before 1 month of challan date to settle

if distributor doesnt settle within 1 month then distributor's counsellor should get notified..

if 40 days after challan date, it doesnt get settled then it should be flagged in the jivadaya_Admin report...

**Comment by slddrns** [comment]
Done

**Comment by slddrns** [comment]
Done
