### ISSUE TITLE
Jivadaya Module - Followup report

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#202]
similar to followup grid in unsettled challan report...

ps: 
1. also make the dates as date/time in the calendar control..
2. rename 'StartDate' as 'ContactDate' and 'EndDate' as 'ReminderDate' (on ui only)
3. Also include icsid of followupwith (as first column)
4. include category
5. Status to be a drop-down of OPEN/CLOSE
only refresh icon, in followup report..CRUD in unsettled report

search/sort for all columns

**Comment by slddrns** [comment]
Done
