### ISSUE TITLE
Not able to do master data management for city, state and country

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#219]

**Comment by pkaushal** [comment]
Pls execute

insert into requestmap (version,config_attribute,url) values(0,'ROLE_ADMIN,ROLE_NVCC_ADMIN','/city/**');
insert into requestmap (version,config_attribute,url) values(0,'ROLE_ADMIN,ROLE_NVCC_ADMIN','/state/**');
insert into requestmap (version,config_attribute,url) values(0,'ROLE_ADMIN,ROLE_NVCC_ADMIN','/country/**');

and restart server (or quick way is to edit any existing requestmap without any change)

**Comment by slddrns** [comment]
I tried both ways... but it is still giving the error 'Sorry, you're not authorized to view this page'.

**Comment by pkaushal** [comment]
pls do db/dataservice way...this is solved problem..
