### ISSUE TITLE
Donation Module: RB Series can be any length of letters

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#239]
implement as per the comment in the beginning  of donation/bulkdonation1

also in ,

def returnReceiptbook of DonationService

**Comment by slddrns** [comment]
Receipt books with RB series more than one character are getting created. But two receipt books of the same number got created.
![image](https://user-images.githubusercontent.com/20815605/33326806-f54d9372-d47b-11e7-93c2-9c39b8f9787a.png)
