### ISSUE TITLE
Donation Module - ECS Process

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#242]
Please document the wiki process...

Need to assign the Donation Executive and ECS Donor roles first..

The basic process is
1. For every individual enrolled in this scheme,
[folk-ecs-sample.txt](https://github.com/kstsvcs/ics/files/1503501/folk-ecs-sample.txt)

1.a. Search the individual record and open the 'Show Individual' page
1.b. Associate the 'SchemeMember' (from the corresponding link)
1.b.a. In  the create scheme member page, please leave centre as blank. The most important field is ConsumerNo ie a unique identifier that is used later in many steps
1.b. Also provide commitment , ensuring that the external no. is consumer no, is specified
2. For uploading, pls use the relevant option and attached sample file.
2.a. Initially it will show the data on screen, then after review/correction of errors, if any, you can actually upload the data as donation records. Finally they can be converted to donations from the relevant options.

**Comment by slddrns** [comment]
Done
