### ISSUE TITLE
Jivadaya - Not able to edit ack donation entry

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#291]

**Comment by slddrns** [comment]
‘Update Pay’ option is not working, when the the payment is done through “Against Donation” mode. It is showing “ Receipt already GENERATED by ACCNT Dept.” PFA.
![cannot update donation](https://user-images.githubusercontent.com/20815605/34823441-5b4e524c-f6f0-11e7-9106-3e67b96376b9.jpg)

**Comment by slddrns** [comment]
Resolved

**Comment by slddrns** [comment]
A separate dialog is required for editing the AckPay entry like Update Pay. Right now update is inline.

**Comment by susanta4** [comment]
Resolved. Please check..
