### ISSUE TITLE
Course Module : changes on http://localhost:8080/ics/course/gridlist

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#423]
- for individualCourse grid, need a button to add by role, also add by searching  the individual, same concept in the instructor grid on masterCourse..

- upload buttons should have file formats specified
- incorrect timestamp on payment date
- JIT creation of ACKDonor
- bulk attendance upload
- individualcourse to have another button to create individualAssessment records for the selected data..dialog should show a drop down of all assessments for the course..
-- master course grid list
-- instructor list data should be as per type..teeacher/student..only non students should be shown here...students should be seen in the course gridlist page..crud should have autocomplete for legal name..other data should get populated accrodingly..only show name (not legal and initiated both)
-- content list -> department should be last col...this is the convention..
-- assessment -> autocomplete for incharge...
-- individualassessment -> remove question paper, and event registration..
-- individualassessment -> download/export and upload the same with scores populated..
[to be discussed..later]
-- completed button?

**Comment by susanta4** [comment]
What about complete button...
