### ISSUE TITLE
Course - ajaxDenied on legalname while adding record to Individual Course list and Individual Assessment list

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#439]
https://server.iskconapp.com/ics/individual/allIndividualsAsJSON_JQ?term=sld
I am logged in with the role CourseAdmin
Individual Course list - page = course/gridlist
Individual Assessment list - page = course/masterCourseGridlist
Please change the dialog name for adding record to Individual Course list also

**Comment by susanta4** [comment]
Pls try with this - 
update requestmap set config_attribute=concat(config_attribute,',ROLE_COURSE_ADMIN') where url='/individual/allIndividualsAsJSON_JQ/**';
update requestmap set config_attribute=concat(config_attribute,',ROLE_COURSE_ADMIN') where url='/event*/*/**';
