### ISSUE TITLE
Course - Attendance sheet downloaded with blank values

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#499]
Downloading attendance sheet downloads blank values in csv. Getting following error at the server:

| Error 2018-04-13 10:21:44,972 [http-bio-8080-exec-8] ERROR [/ics].[default]  - Servlet.service() for servlet [default] in context with path [/ics] threw exception [Request processing failed; nested exception is org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response] with root cause
Message: getOutputStream() has already been called for this response
    Line | Method
->>  120 | getWriter in net.bull.javamelody.FilterServletResponseWrapper
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|     15 | run       in E__SLDD_Projects_ICS_ics_grails_app_views_error_gsp
|    150 | invoke .  in net.bull.javamelody.JspWrapper
|    285 | invoke    in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

**Comment by susanta4** [comment]
Fixed.
