### ISSUE TITLE
Course - Once assessment is added, page has to be refreshed for adding another assessment 

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#500]
Every time assessment has to be added, the page needs to be refreshed. If page is not refreshed before adding assessment then incharge.id gets passed twice in the url and the record does not get added

http://localhost:8080/ics/assessment/jq_assessment_edit?fromPage=masterCourseGridlist&course.id=1&incharge.id=7&incharge.id=7

**Comment by susanta4** [comment]
Fixed..
