### ISSUE TITLE
Jivadaya - Reports required

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#526]
Following reports are required:
1. STOCK AS ON ANY DATE. eg: What was the stock on 25/07/16?
2. CONSOLIDATED SALE REPORT.
3. PURCHASE ENTRY/INWARD ENTRY consolidated Report.
4. Total Challan Issued/Settled/Open in a particular period REPORT
5. Chk Pending Challan Report....(ONLY 100 entries...how come??)
6. Bucket Report/Unsettlled Challan Ageing Report (Sample in the page you were writing today's meeting notes)
7. Diff settlement mechanism for challans not going to settle at any cost.(eg: Those pending since 2014 and authority has permitted to waive off....it should reflect in our losses.)

**Comment by slddrns** [comment]
7. Add distributor as non-mandatory input field to the profit report. Include both issued and settled challans in the output.

**Comment by susanta4** [comment]
option 3 and 7 resolved.
