### ISSUE TITLE
Jivadaya - Error on creating Ack Payment

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#528]
Cannot get property 'individual' on null object. Stacktrace follows:
Message: Cannot get property 'individual' on null object
    Line | Method
->>  489 | createDonationRecord     in ics.ChallanService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    224 | addAckPayDonationRecord  in     ''
|    184 | doCall . . . . . . . . . in GrailsMelodyGrailsPlugin$_closure4_closure16_closure17
|   1465 | saveAckPayDonationRecord in ics.ChallanController
|    150 | invoke . . . . . . . . . in net.bull.javamelody.JspWrapper
|    285 | invoke                   in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter . . . . . . . . in net.bull.javamelody.MonitoringFilter
|    180 | doFilter                 in     ''
|   1145 | runWorker . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                      in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . .  in java.lang.Thread

**Comment by susanta4** [comment]
fixed..
