### ISSUE TITLE
Jivadaya - OUT OF STOCK!! Warning for books out of stock

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#530]
1. Sometimes dvt may not know that a particular book is not there and then he creates the challan, but later comes to know that the particular book is out of stock.
2. Another advantage is that this will force the manager to regularly update the stock, in case he is lazy in doing so.
3. Implementation: Suppose i want 5 BG M, but there are 3 available. So as soon as i enter 5 BG M in Order, a pop up should arise saying "Sorry ! Out of Stock !! Available: 3"

**Comment by susanta4** [comment]
Fixed
