### ISSUE TITLE
Course - Provide a button for attendance sheet on Event List for Course grid

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#543]
On course/gridlist page, Event List for Course grid, provide a button called 'AS' clicking on which a dialog should be opened on which a table with following data should be present:
1. IcsId
2. Name (sorted alphabetically)
3. Phone
4. Email id
5. Current Status (no. of classes attended / no. of classes conducted ex. 3/5)
6. Last 3 statuses (3 columns for last 3 classes)
7. Column for signature
Provide Print and Cancel buttons for the dialog.

Export should also be done in the same format.

**Comment by susanta4** [comment]
currently option 6 not done.
