### ISSUE TITLE
Donation - Error on the server on logging in with the role donation executive and clicking DonationRecord List button

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#553]
---------------------jq_alldonationrecord_list-----------
centre is null
2018-04-26 16:33:12,919 [http-bio-8080-exec-1] DEBUG ics.DonationRecordController  - In donationRecordDataWithFilters with params: [sord:desc, donation_date:undefined, selectedcenter:undefined, page:1, nd:1524740592744, sidx:id, rows:10, _search:false, action:jq_alldonationrecord_list, controller:donationRecord]
2018-04-26 16:33:13,064 [http-bio-8080-exec-1] DEBUG ics.HelperService  - Got schemes..[]
| Error 2018-04-26 16:33:13,103 [http-bio-8080-exec-1] ERROR util.JDBCExceptionReporter  - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') order by this_.id desc limit 10' at line 1
| Error 2018-04-26 16:33:13,114 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - MySQLSyntaxErrorException occurred when processing request: [GET] /ics/donationRecord/jq_alldonationrecord_list - parameters:
sord: desc
donation_date: undefined
selectedcenter: undefined
page: 1
nd: 1524740592744
sidx: id
rows: 10
_search: false
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') order by this_.id desc limit 10' at line 1. Stacktrace follows:
Message: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') order by this_.id desc limit 10' at line 1
    Line | Method
->>  411 | handleNewInstance             in com.mysql.jdbc.Util
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    386 | getInstance                   in     ''
|   1052 | createSQLException . . . . .  in com.mysql.jdbc.SQLError
|   3597 | checkErrorPacket              in com.mysql.jdbc.MysqlIO
|   3529 | checkErrorPacket . . . . . .  in     ''
|   1990 | sendCommand                   in     ''
|   2151 | sqlQueryDirect . . . . . . .  in     ''
|   2625 | execSQL                       in com.mysql.jdbc.ConnectionImpl
|   2119 | executeInternal . . . . . . . in com.mysql.jdbc.PreparedStatement
|   2281 | executeQuery                  in     ''
|     96 | executeQuery . . . . . . . .  in org.apache.commons.dbcp.DelegatingPreparedStatement
|    403 | doExecute                     in net.bull.javamelody.JdbcWrapper
|    128 | invoke . . . . . . . . . . .  in net.bull.javamelody.JdbcWrapper$StatementInvocationHandler
|    285 | invoke                        in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|     55 | <init> . . . . . . . . . . .  in grails.orm.PagedResultList
|   1612 | invokeMethod                  in grails.orm.HibernateCriteriaBuilder
|   1278 | donationRecordDataWithFilters in ics.DonationRecordController
|   1210 | doCall                        in ics.DonationRecordController$_closure22
|    150 | invoke . . . . . . . . . . .  in net.bull.javamelody.JspWrapper
|    285 | invoke                        in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter . . . . . . . . . .  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter                      in     ''
|   1145 | runWorker . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run                           in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . . . in java.lang.Thread

**Comment by susanta4** [comment]
I am not getting any error, may be it not getting scheme of logged in user. Pls check.
