### ISSUE TITLE
Admin - CostCenter dropdown not populated for adding/editing department

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#565]
centre/list page
login as system admin
There is a cost center GEN present which is autocreated.
This does not show in the CostCenter dropdown not populated while adding/editing department

**Comment by susanta4** [comment]
when using bootupCenter ,Coscenter is created only for donation module. Pls create a new bootupCenter in which  donation module is also selected and then test on ur issues.

**Comment by slddrns** [comment]
I had selected donation module when using bootupCenter. That is how I am logging in as donation admin.

**Comment by susanta4** [comment]
Now u can try once again with the latest code.
