### ISSUE TITLE
Course - Issues while uploading courses

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#581]
1. In the csv file column sequence it is mentioned that the Id can be optional. But in the code the case in which id is not given is not handled. How can the user know what id to give next?

2. When I give id and upload the file, I get following error at the server:

| Error 2018-05-22 20:06:34,275 [http-bio-8080-exec-3] ERROR errors.GrailsExceptionResolver  - MissingMethodException occurred when processing request: [POST] /ics/course/uploadCourses
No signature of method: ics.EventService.uploadCourses() is applicable for argument types: ([Ljava.lang.String;, java.lang.String) values: [[17, IDC1, Uploading, RKM, English, IDC, ...], ...]
Possible solutions: uploadcourses(java.lang.Object, java.lang.String). Stacktrace follows:
Message: No signature of method: ics.EventService.uploadCourses() is applicable for argument types: ([Ljava.lang.String;, java.lang.String) values: [[17, IDC1, Uploading, RKM, English, IDC, ...], ...]
Possible solutions: uploadcourses(java.lang.Object, java.lang.String)
    Line | Method
->>  170 | doCall        in GrailsMelodyGrailsPlugin$_closure4_closure16_closure17
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|   1119 | doCall        in ics.CourseController$_uploadCourses_closure28$$EQsmspQ1
|     34 | eachLine . .  in org.grails.plugins.csv.CSVReaderUtils
|    126 | doCall        in CsvGrailsPlugin$_closure4_closure8
|   1116 | uploadCourses in ics.CourseController$$EQsmsoDl
|    202 | doFilter      in net.bull.javamelody.MonitoringFilter
|    180 | doFilter . .  in     ''
|   1145 | runWorker     in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run           in java.lang.Thread

**Comment by pkaushal** [comment]
Cleared today's milestone since this scenario is very rare ie some one wants to bulk upload courses...
