### ISSUE TITLE
MB Module - modify Config page

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#587]
- accessible to ROLE_MB_SEC and ROLE_MB_ADMIN
this will have links to various pages
- a jqgrid to show all castes (backend query
select caste,count(1) c from individual where caste is not null group by caste)
- a jqgrid to show all sub-castes (backend query 
select caste,count(1) c from individual where caste is not null group by caste)
-- both these grids should have merge concept..since its a string so the implementation should be to select 1 or many rows...then enter a text in a dialog..then for all the selected rows, the value should change to the provided one..

-- For ISKCON Centres,Occupation and Spiritual masters, create appropriate links...
and call mb/createAttributes
actual condition similar to:
<g:set var="iskconCentres" value="${ics.AttributeValue.findAllByAttribute(ics.Attribute.findByDomainClassNameAndDomainClassAttributeNameAndCategory('Mb','iskcon_centre','Config'))?.collect{it.value}}" />
<g:set var="spiritualMasters" value="${ics.AttributeValue.findAllByAttribute(ics.Attribute.findByDomainClassNameAndDomainClassAttributeNameAndCategory('Mb','sp_master','Config'))?.collect{it.value}}" />
<g:set var="occupation" value="${ics.AttributeValue.findAllByAttribute(ics.Attribute.findByDomainClassNameAndDomainClassAttributeNameAndCategory('Mb','occupation','Config'))?.collect{it.value}}" />

**Comment by susanta4** [comment]
done
