### ISSUE TITLE
Course - Errors on server on loading page course/masterCourseGridlist

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#623]
Could not initialize class ics.ContentController$_closure9_closure11. Stacktrace follows:
Message: Executing action [jq_content_list] of controller [ics.ContentController]  caused exception: Runtime error executing action
    Line | Method
->>  150 | invoke    in net.bull.javamelody.JspWrapper
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    285 | invoke    in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by ControllerExecutionException: Runtime error executing action
->>  150 | invoke    in net.bull.javamelody.JspWrapper
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    285 | invoke    in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by InvocationTargetException: null
->>  150 | invoke    in net.bull.javamelody.JspWrapper
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    285 | invoke    in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run       in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . in java.lang.Thread

Caused by NoClassDefFoundError: Could not initialize class ics.ContentController$_closure9_closure11
->>  151 | doCall    in ics.ContentController$_closure9
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    150 | invoke    in net.bull.javamelody.JspWrapper
|    285 | invoke .  in net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler
|    202 | doFilter  in net.bull.javamelody.MonitoringFilter
|    180 | doFilter  in     ''
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by susanta4** [comment]
I could not find any issue with this, is there any special condition when its occurring?

**Comment by slddrns** [comment]
Could not reproduce...
