### ISSUE TITLE
Seva Module : multiple issues

### ISSUE THREAD

**Issue by pkaushal** [kstsvcs/ics#626]
- getIndividualforVue  is not multitenant
- there are some permission issues
- need to create a simple doc describing  the entire process
- shortlisted/assigned gets duplicated
- sms/email
- start/stop timestamp to be captured (using chartitem)
- skill level to be captured (using Skill and IndividualSkill)
- vue page for clor to propose clees for various seva allotment

**Comment by susanta4** [comment]
all are not tested
