### ISSUE TITLE
Admin Module - ICS Usage dashboard

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#738]
In the System Admin (and also super admin), create a new dashboard (under the User tab) to show basic statistics module wise (in a date range..default current calendar month)

for eg
accounts & seva office users only
1. login time, log out time, how long was active on the system--- this is to track how many hours user worked
2. how many new receipts enterd
3. how many ICS merge done
4. Dummy donor linked
5. data entry done for existing
6. which PC the user opened the id frm

**Comment by susanta4** [comment]
test required
