### ISSUE TITLE
MB - Initiated name of candidate not getting saved

### ISSUE THREAD

**Issue by slddrns** [kstsvcs/ics#755]
When a candidate registers, 4 letter string is accepted as initiated name.
When he completes the profile through mb/editProfile page, if same 4 letter string is given, it is not accepted and a message 'Invalid format' is displayed. If the initiated name is now modified to 5+3 string, the error message goes away but after saving it again changes to the initially given 4 letter string and the error message appears again.
Initiated name can be 'Ram Das' so 3+3 should also be allowed.

**Comment by slddrns** [comment]
List of attributes of individual domain used for mb profile:
legalName
initiatedName
dob
iskconCentre
isMale
varna
profession
companyName
designation
motherTongue
languagePreference(?)
picFileURL(?)
firstInitiation
secondInitiation
education
avatar
introductionDate
sixteenRoundsDate
chantingSinceDate
numRounds
firstInitiationStatus(?)
religion
eduCat(?)
eduQual(?)
skills(?)
frequencyOfTempleVisits
likesInKc
dislikesInKc
regulatedSince(?)
otherLanguages(?)
origin
caste
subCaste
income
height
houseDescription
nationality
centre
inStation
pob

**Comment by slddrns** [comment]
from the code (editProfile.gsp):
legalName
initiatedName
isMale
dob
pob
iskconCentre
origin
caste
subCaste
varna
height
motherTongue
nationality
income

**Comment by susanta4** [comment]
need to check for initiated name issue
