### ISSUE TITLE
PoS Module - Payment/DonationRecord redesign

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#771]
we are currently creating DR for each payment...instead of this, summary value should get sent from the DTR page, 
ie for a given day, the DTR would show total collections by category and mode...there should be a button to 'Submit' these....then for each category/mode combination (apart from Against%) a DR should get created...the scheme would be matched on category and department...receipt no of DR should get auto generated...

**Comment by susanta4** [comment]
pending....
