### ISSUE TITLE
PoS Module - Duplicate 'DummyCashSale' person got created..

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#850]
logs from live...looks like some cleanup was missing..(personTo:personId:589, email:, phone:, personId:5468 in the second call)

Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,192 [http-bio-443-exec-11] DEBUG ics.InvoiceController  - createInvoiceEntryVue :[items:[{"id":8899,"name":"MRT Tusharth Pathik","code":"9789381283073","quantity":1,"unit":"PIECES","rate":200,"taxRate":0,"totalAmount":200,"description":""}], personTo:, email:, phone:, personId:5468, personResultSource:INDIVIDUAL, extraAmount:0, discountAmount:0, comments:, departmentBy.id:, departmentBy:[id:], type:SALES, isCashSale:CASH, paymentData:{"modeId":"","amount":200,"paymentDate":null,"details":"","bankName":"","bankBranch":"","instrumentNo":""}, isItemReturn:no, returnedInvoiceNo:, action:createInvoiceEntryVue, controller:invoice]
Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,234 [http-bio-443-exec-11] DEBUG ics.InvoiceController  - invoiceDate  :null
Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,242 [http-bio-443-exec-11] DEBUG ics.InvoiceController  - person : null
Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,277 [http-bio-443-exec-11] DEBUG ics.InvoiceService  - createInvoice:[items:[{"id":8899,"name":"MRT Tusharth Pathik","code":"9789381283073","quantity":1,"unit":"PIECES","rate":200,"taxRate":0,"totalAmount":200,"description":""}], personTo:personId:589, email:, phone:, personId:5468, personResultSource:INDIVIDUAL, extraAmount:0, discountAmount:0, comments:, departmentBy.id:, departmentBy:[id:], type:SALES, isCashSale:CASH, paymentData:{"modeId":"","amount":200,"paymentDate":null,"details":"","bankName":"","bankBranch":"","instrumentNo":""}, isItemReturn:no, returnedInvoiceNo:, action:createInvoiceEntryVue, controller:invoice, userName:Sarita77, status:PREPARED, keyFromAlias:true]
Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,351 [http-bio-443-exec-11] DEBUG ics.InvoiceController  - Inside cash sale.....
Jun  9 10:04:06 server authbind: 2019-06-09 10:04:06,352 [http-bio-443-exec-11] DEBUG ics.InvoiceService  - savePaymentReference  :[mode.id:2, amount:200, paymentDate:09-06-2019, details:, invoiceids:766, comments:, department.id:83]
Jun  9 10:06:23 server authbind: 2019-06-09 10:06:23,336 [http-bio-443-exec-16] DEBUG ics.InvoiceController  - Inside jq_invoice_list with params : [type:SALES, _search:false, nd:1560089183133, rows:10, page:1, sidx:, sord:desc, action:jq_invoice_list, controller:invoice]

Jun  9 10:13:53 server authbind: 2019-06-09 10:13:53,370 [http-bio-443-exec-8] DEBUG ics.InvoiceController  - payModes : [AgainstDonation, AgainstIDT, Card, Cash, Cheque, DirectDeposit, ECS, Kind, NEFT, ONLINE, RTGS, Transfer]
Jun  9 10:14:01 server authbind: 2019-06-09 10:14:01,300 [http-bio-443-exec-3] DEBUG ics.InvoiceController  - createInvoiceEntryVue :[items:[{"id":8989,"name":"Coffe Belgaum 577","code":"SK85373430","quantity":1,"unit":"PIECES","rate":35,"taxRate":5,"totalAmount":35,"description":""}], personTo:, email:, phone:, personId:, personResultSource:, extraAmount:0, discountAmount:0, comments:, departmentBy.id:, departmentBy:[id:], type:SALES, isCashSale:CASH, paymentData:{"modeId":"","amount":35,"paymentDate":null,"details":"","bankName":"","bankBranch":"","instrumentNo":""}, isItemReturn:no, returnedInvoiceNo:, action:createInvoiceEntryVue, controller:invoice]
Jun  9 10:14:01 server authbind: 2019-06-09 10:14:01,340 [http-bio-443-exec-3] DEBUG ics.InvoiceController  - invoiceDate  :null
Jun  9 10:14:01 server authbind: 2019-06-09 10:14:01,376 [http-bio-443-exec-3] ERROR errors.GrailsExceptionResolver  - NonUniqueResultException occurred when processing request: [GET] /ics/invoice/createInvoiceEntryVue
Jun  9 10:14:01 server authbind: query did not return a unique result: 2. Stacktrace follows:
Jun  9 10:14:01 server authbind: org.hibernate.NonUniqueResultException: query did not return a unique result: 2
Jun  9 10:14:01 server authbind: at grails.orm.HibernateCriteriaBuilder.invokeMethod(HibernateCriteriaBuilder.java:1620)
Jun  9 10:14:01 server authbind: at ics.InvoiceController.createInvoiceEntryVue(InvoiceController.groovy:2580)
Jun  9 10:14:01 server authbind: at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:150)
Jun  9 10:14:01 server authbind: at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:285)
Jun  9 10:14:01 server authbind: at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
Jun  9 10:14:01 server authbind: at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)

**Comment by susanta4** [comment]
resolved.need to be tested
