### ISSUE TITLE
Individual Module : Activity Tracker

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#983]
The Followup/Objective/SR on the indiividual/show page would show the data for the respective individual.
Whereas on the individual/activityTracker page(s), it would show for the logged in user (unless its an ActivityAdmin, in which case it would show for the entire centre)
In the individual/show/followup, 1 more grid needs to be added
Susanta pr: to add missing logic and expose it on the app (new ActivityTracker module, visible to only those who have ActivityUser role); 
Narayan pr: to test from all perspective, implement any missing sort/search etc and finally document..testing should also cover multi-tenant scenario as well

**Comment by susanta4** [comment]
Admin CURD need to be implemented
