### ISSUE TITLE
EMS Module - All Expenses Report

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#988]
on project/reports,

equivalent to "
select ccat.name cost_category, cc.name cost_center,p.ref earNo,date_format(p.submit_date,'%d-%m-%y') submit_date,l.name ledge_head,e.amount,e.description,date_format(e.invoice_date,'%d-%m-%y') invoice_date, e.invoice_no,e.invoice_raised_by,e.invoice_available,date_format(p.settle_date,'%d-%m-%y') settle_date from project p, expense e, payment_mode pm,cost_category ccat, cost_center cc,ledger_head l where p.cost_center_id=cc.id and cc.cost_category_id=ccat.id and e.project_id=p.id and e.invoice_payment_mode_id=pm.id and p.status='SETTLED_REPORT' and pm.name='Cash' and e.ledger_head_id=l.id and e.status!='DELETED'"

with various filters, ie ccat, cc, date range, payment mode,ledger

**Comment by susanta4** [comment]
filter has to be implemented ccat, cc, date range, payment mode,ledger
