### ISSUE TITLE
Donation Module : Bulk Quick Issue for multi-tenant doesnt work

### ISSUE THREAD

**Issue by kstsvcs** [kstsvcs/ics#994]
In the multi-tenant scenario, create RBs in bulk lets say A1-A5, 10 pages each
then if you try to 'quick issue bulk', then there is an error msg saying 'invalid state or already issued' (something like this)
To be simulated and fixed by Narayan pr and cross verified by Susanta pr

**Comment by susanta4** [comment]
Pending...
